### ISSUE TITLE
No enum constant org.bukkit.Difficulty.EAZY

### ISSUE THREAD

**Issue by Chiloven945** [Dev7ex/FacilisCommon#2]
```
[00:51:06] [Server thread/ERROR]: Could not pass event PluginEnableEvent to FacilisCommon v1.0.2-SNAPSHOT
java.lang.IllegalArgumentException: No enum constant org.bukkit.Difficulty.EAZY
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at org.bukkit.Difficulty.valueOf(Difficulty.java:10) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at com.dev7ex.multiworld.world.DefaultWorldConfiguration.getWorldHolder(DefaultWorldConfiguration.java:224) ~[MultiWorld-Bukkit-1.4.3-SNAPSHOT.jar:?]
	at com.dev7ex.multiworld.world.DefaultWorldConfiguration.getWorldHolders(DefaultWorldConfiguration.java:243) ~[MultiWorld-Bukkit-1.4.3-SNAPSHOT.jar:?]
	at com.dev7ex.multiworld.world.DefaultWorldProvider.onEnable(DefaultWorldProvider.java:48) ~[MultiWorld-Bukkit-1.4.3-SNAPSHOT.jar:?]
	at com.dev7ex.common.bukkit.plugin.service.ServiceManager.onEnable(ServiceManager.java:35) ~[FacilisCommon-Bukkit-1.0.2-SNAPSHOT.jar:?]
	at com.dev7ex.common.bukkit.BukkitCommonPlugin.handlePluginEnable(BukkitCommonPlugin.java:80) ~[FacilisCommon-Bukkit-1.0.2-SNAPSHOT.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-45]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-45]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-45]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:200) ~[paper-1.20.1.jar:git-Paper-45]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-45]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-45]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-45]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-45]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
Use Paper1.20.1

**Comment by Dev7ex** [comment]
Did you change anything manually in the world.yml?

**Comment by Dev7ex** [comment]
It seems that there is no answer anymore. The world.yml should not be edited manually. Use the appropriate command. 

You wrote EAZY instead of EASY that triggers the error
