### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant com.dev7ex.multiworld.api.world.WorldDefaultProperty.LOAD_AUTO

### ISSUE THREAD

**Issue by Naimadx123** [Dev7ex/FacilisCommon#6]
```
[21:25:52 INFO]: [MultiWorld] Loading server plugin MultiWorld v1.6.7-SNAPSHOT
[21:25:52 INFO]: [MultiWorld] Adding missing config entry: settings.defaults.auto-load-enabled
[21:25:52 INFO]: [MultiWorld] Adding missing config entry: settings.defaults.auto-unload-enabled
[21:25:52 INFO]: [MultiWorld] Adding missing config entry: settings.defaults.hunger-enabled
[21:25:52 INFO]: [MultiWorld] Adding missing config entry: settings.defaults.keep-spawn-in-memory
[21:25:52 INFO]: [MultiWorld] Adding missing config entry: settings.defaults.redstone-enabled
[21:25:52 INFO]: [MultiWorld] Adding missing config entry: settings.defaults.weather-enabled
[21:25:52 ERROR]: [MultiWorld] Error initializing plugin 'MultiWorld-Bukkit-1.6.7-SNAPSHOT.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant com.dev7ex.multiworld.api.world.WorldDefaultProperty.LOAD_AUTO
        at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at MultiWorld-Bukkit-1.6.7-SNAPSHOT.jar/com.dev7ex.multiworld.api.world.WorldDefaultProperty.valueOf(WorldDefaultProperty.java:17) ~[MultiWorld-Bukkit-1.6.7-SNAPSHOT.jar:?]
        at MultiWorld-Bukkit-1.6.7-SNAPSHOT.jar/com.dev7ex.multiworld.MultiWorldConfiguration.lambda$load$0(MultiWorldConfiguration.java:65) ~[MultiWorld-Bukkit-1.6.7-SNAPSHOT.jar:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at MultiWorld-Bukkit-1.6.7-SNAPSHOT.jar/com.dev7ex.multiworld.MultiWorldConfiguration.load(MultiWorldConfiguration.java:65) ~[MultiWorld-Bukkit-1.6.7-SNAPSHOT.jar:?]
        at MultiWorld-Bukkit-1.6.7-SNAPSHOT.jar/com.dev7ex.multiworld.MultiWorldPlugin.onLoad(MultiWorldPlugin.java:63) ~[MultiWorld-Bukkit-1.6.7-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-130-b1b5d4c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Naimadx123** [comment]
https://github.com/Dev7ex/MultiWorld/issues/49#issuecomment-2324610086
