### ISSUE TITLE
FacilisCommon has detected an error in the plugin MultiWorld

### ISSUE THREAD

**Issue by IANBLK** [Dev7ex/FacilisCommon#7]
[03:10:50 ERROR] [STDERR]: java.lang.IllegalArgumentException: Illegal dimension (CUSTOM)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.craftbukkit.v1_20_R1.CraftServer.createWorld(CraftServerMixin.java:1096)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.Bukkit.createWorld(Bukkit.java:703)
[03:10:50 ERROR] [STDERR]:      at com.dev7ex.multiworld.world.DefaultWorldManager.loadWorld(DefaultWorldManager.java:555)
[03:10:50 ERROR] [STDERR]:      at com.dev7ex.multiworld.world.DefaultWorldProvider.onEnable(DefaultWorldProvider.java:93)
[03:10:50 ERROR] [STDERR]:      at com.dev7ex.common.bukkit.plugin.module.PluginModuleManager.enableAllModules(PluginModuleManager.java:49)
[03:10:50 ERROR] [STDERR]:      at com.dev7ex.common.bukkit.BukkitCommonPlugin.handlePluginEnable(BukkitCommonPlugin.java:74)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:349)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServerMixin.java:546)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.20.1-1.0.5-1a8925b/org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServerMixin.java:460)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.handler$zmj000$arclight$enablePlugins(MinecraftServerMixin.java:2137)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:385)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:308)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:164)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2028)
[03:10:50 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:251)
[03:10:50 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by Dev7ex** [comment]
1. is this a mistake by multiworld and not FacilisCommon 

2. is it due to the custom type in the next update there will be a fix in which it can no longer be used?
